// src/utils/chennaiMncData.js

export const CHENNAI_TECH_ZONES = [
  { id: "all", label: "All Tech Hubs", count: 16 },
  { id: "omr", label: "OMR IT Corridor", count: 5 },
  { id: "dlf", label: "DLF Cybercity (Porur)", count: 4 },
  { id: "siruseri", label: "Siruseri IT Park", count: 2 },
  { id: "guindy", label: "Guindy & Olympia", count: 3 },
  { id: "mepz", label: "MEPZ & Guduvanchery", count: 2 },
];

export const CHENNAI_CATEGORIES = [
  "All Types",
  "Product MNC",
  "SaaS Unicorn",
  "IT Services & Consulting",
  "FinTech & Banking",
];

export const CHENNAI_MNC_COMPANIES = [
  {
    id: "mnc-1",
    name: "Zoho Corporation",
    category: "SaaS Unicorn",
    zone: "mepz",
    zoneLabel: "Guduvanchery & Tenkasi",
    location: "Estancia IT Park, Guduvanchery, Chennai",
    packageRange: "₹8.4 LPA - ₹12.0 LPA",
    minCgpa: 7.0,
    roles: ["Member Technical Staff (MTS)", "Software Developer", "UI/UX Engineer"],
    skills: ["Java", "C", "Data Structures", "OOPs", "Web Architecture"],
    logo: "https://www.zoho.com/favicon.ico",
    website: "https://www.zoho.com/careers",
    hiringSeason: "July - September (Annual Campus Drive)",
    description: "Global SaaS leader crafting suite of 55+ business applications used by over 100 million users worldwide.",
    featured: true,
  },
  {
    id: "mnc-2",
    name: "Tata Consultancy Services (TCS)",
    category: "IT Services & Consulting",
    zone: "siruseri",
    zoneLabel: "Siruseri IT Park",
    location: "TCS Siruseri Campus & TCS Olympus, Chennai",
    packageRange: "₹3.6 LPA - ₹7.5 LPA",
    minCgpa: 6.0,
    roles: ["Digital Systems Engineer", "Ninja Developer", "Cloud Analyst"],
    skills: ["Python", "Java", "SQL & DBMS", "Aptitude"],
    logo: "https://www.tcs.com/favicon.ico",
    website: "https://www.tcs.com/careers",
    hiringSeason: "August - October (TCS NQT National Drive)",
    description: "India's largest IT exporter operating Asia's largest single-location IT park at Siruseri, Chennai.",
    featured: true,
  },
  {
    id: "mnc-3",
    name: "Cognizant (CTS)",
    category: "IT Services & Consulting",
    zone: "mepz",
    zoneLabel: "MEPZ Tambaram & DLF",
    location: "MEPZ SEZ Tambaram / DLF IT Park, Chennai",
    packageRange: "₹4.0 LPA - ₹6.75 LPA",
    minCgpa: 6.0,
    roles: ["GenC Next Developer", "GenC Software Engineer", "Quality Analyst"],
    skills: ["Java", "SQL", "HTML/CSS/JS", "Problem Solving"],
    logo: "https://www.cognizant.com/favicon.ico",
    website: "https://www.cognizant.com/careers",
    hiringSeason: "August - November (GenC Campus Drive)",
    description: "Fortune 500 IT powerhouse with massive delivery centers in MEPZ Tambaram and DLF Cybercity.",
    featured: true,
  },
  {
    id: "mnc-4",
    name: "Amazon India",
    category: "Product MNC",
    zone: "omr",
    zoneLabel: "Perungudi OMR",
    location: "World Trade Center, Perungudi, Chennai",
    packageRange: "₹14.0 LPA - ₹28.0 LPA",
    minCgpa: 7.5,
    roles: ["Software Development Engineer (SDE-1)", "Quality Assurance Engineer"],
    skills: ["Data Structures", "Algorithms", "System Design", "AWS", "Java/C++"],
    logo: "https://www.amazon.com/favicon.ico",
    website: "https://www.amazon.jobs",
    hiringSeason: "September - December (Amazon WOW & Off-Campus)",
    description: "Global e-commerce and AWS cloud giant operating major development centers in Chennai's OMR corridor.",
    featured: true,
  },
  {
    id: "mnc-5",
    name: "PayPal India",
    category: "FinTech & Banking",
    zone: "guindy",
    zoneLabel: "Guindy & Olympia",
    location: "Olympia Tech Park, Guindy, Chennai",
    packageRange: "₹12.0 LPA - ₹22.0 LPA",
    minCgpa: 7.5,
    roles: ["Software Engineer - FinTech", "Data Engineer", "Security Analyst"],
    skills: ["Java", "Distributed Systems", "Node.js", "SQL", "Cryptography"],
    logo: "https://www.paypal.com/favicon.ico",
    website: "https://www.paypal.com/jobs",
    hiringSeason: "October - January (Campus & Off-Campus)",
    description: "Pioneer in global digital payment solutions, housing its largest technology center outside the US at Guindy.",
    featured: true,
  },
  {
    id: "mnc-6",
    name: "Accenture India",
    category: "IT Services & Consulting",
    zone: "omr",
    zoneLabel: "Sholinganallur OMR",
    location: "Tek Towers Sholinganallur & DLF IT Park, Chennai",
    packageRange: "₹4.5 LPA - ₹6.5 LPA",
    minCgpa: 6.0,
    roles: ["Advanced Application Associate", "Associate Software Engineer"],
    skills: ["Python", "Cloud Basics", "Networking", "Pseudocode Debugging"],
    logo: "https://www.accenture.com/favicon.ico",
    website: "https://www.accenture.com/in-en/careers",
    hiringSeason: "August - December (Annual Drive)",
    description: "Leading global professional services company specializing in digital, cloud, and cybersecurity transformation.",
    featured: false,
  },
  {
    id: "mnc-7",
    name: "Freshworks",
    category: "SaaS Unicorn",
    zone: "omr",
    zoneLabel: "Perungudi OMR",
    location: "Global Infocity, Perungudi, OMR, Chennai",
    packageRange: "₹8.0 LPA - ₹15.0 LPA",
    minCgpa: 7.0,
    roles: ["Product Software Engineer", "Frontend Developer", "DevOps Engineer"],
    skills: ["Ruby on Rails", "React.js", "Node.js", "PostgreSQL", "AWS"],
    logo: "https://www.freshworks.com/favicon.ico",
    website: "https://www.freshworks.com/careers",
    hiringSeason: "July - October (Freshworks STS Academy)",
    description: "NASDAQ-listed SaaS unicorn born in Chennai, building AI-powered customer support and CRM software.",
    featured: true,
  },
  {
    id: "mnc-8",
    name: "Barclays Global Service Centre",
    category: "FinTech & Banking",
    zone: "dlf",
    zoneLabel: "DLF Cybercity (Porur)",
    location: "DLF IT Park, Ramapuram, Porur, Chennai",
    packageRange: "₹9.5 LPA - ₹16.0 LPA",
    minCgpa: 7.0,
    roles: ["Graduate Technology Developer", "Risk & Data Analyst"],
    skills: ["Java", "Python", "SQL", "Spring Boot", "Financial Mathematics"],
    logo: "https://home.barclays/favicon.ico",
    website: "https://home.barclays/careers",
    hiringSeason: "September - November",
    description: "Major British universal bank operating technology and engineering innovation labs in DLF Porur.",
    featured: false,
  },
  {
    id: "mnc-9",
    name: "IBM India",
    category: "Product MNC",
    zone: "dlf",
    zoneLabel: "DLF Cybercity (Porur)",
    location: "DLF Cybercity, Block 7, Porur, Chennai",
    packageRange: "₹4.5 LPA - ₹9.0 LPA",
    minCgpa: 6.5,
    roles: ["Associate System Engineer", "Cloud Software Developer"],
    skills: ["Java", "Cloud Computing", "AI Fundamentals", "Linux"],
    logo: "https://www.ibm.com/favicon.ico",
    website: "https://www.ibm.com/in-en/employment",
    hiringSeason: "August - December",
    description: "Global technology and hybrid cloud leader driving AI enterprise software research in Chennai.",
    featured: false,
  },
  {
    id: "mnc-10",
    name: "HCLTech",
    category: "IT Services & Consulting",
    zone: "omr",
    zoneLabel: "Sholinganallur OMR",
    location: "ELCOT SEZ Sholinganallur & Ambattur Industrial Estate",
    packageRange: "₹3.8 LPA - ₹7.0 LPA",
    minCgpa: 6.0,
    roles: ["Graduate Engineer Trainee", "Software Engineer"],
    skills: ["C++", "Java", "Database Design", "Operating Systems"],
    logo: "https://www.hcltech.com/favicon.ico",
    website: "https://www.hcltech.com/careers",
    hiringSeason: "September - January (HCL First Careers)",
    description: "Global technology services major operating expansive campuses in ELCOT SEZ Sholinganallur.",
    featured: false,
  },
  {
    id: "mnc-11",
    name: "Wipro Technologies",
    category: "IT Services & Consulting",
    zone: "omr",
    zoneLabel: "Sholinganallur OMR",
    location: "CDC 5 Campus, Sholinganallur, OMR, Chennai",
    packageRange: "₹3.5 LPA - ₹6.5 LPA",
    minCgpa: 6.0,
    roles: ["Project Engineer (Elite & Turbo)", "Full Stack Trainee"],
    skills: ["Java", "Python", "SQL", "Web Development"],
    logo: "https://www.wipro.com/favicon.ico",
    website: "https://www.wipro.com/careers",
    hiringSeason: "August - November (Wipro NLTH Drive)",
    description: "Global IT services company driving enterprise cloud modernization with major OMR presence.",
    featured: false,
  },
  {
    id: "mnc-12",
    name: "Kaar Technologies",
    category: "IT Services & Consulting",
    zone: "guindy",
    zoneLabel: "Saligramam & Perungudi",
    location: "Saligramam / Perungudi, Chennai",
    packageRange: "₹6.5 LPA",
    minCgpa: 6.5,
    roles: ["SAP Technical Consultant", "Associate Software Engineer"],
    skills: ["C++", "Java", "SQL", "Database Schemas", "Logic"],
    logo: "https://www.kaartech.com/favicon.ico",
    website: "https://www.kaartech.com",
    hiringSeason: "July - August (Active Campus Partner)",
    description: "Pure-play SAP digital transformation consultancy hiring DDGDVC CS graduates for enterprise SAP Cloud roles.",
    featured: true,
  },
  {
    id: "mnc-13",
    name: "Pickyourtrail",
    category: "Product MNC",
    zone: "guindy",
    zoneLabel: "Guindy Tech Corridor",
    location: "Guindy, Chennai",
    packageRange: "₹6.5 LPA - ₹10.0 LPA",
    minCgpa: 7.0,
    roles: ["Frontend Developer", "Full Stack Engineer"],
    skills: ["React.js", "JavaScript (ES6+)", "Node.js", "HTML5/CSS3"],
    logo: "https://pickyourtrail.com/favicon.ico",
    website: "https://pickyourtrail.com/careers",
    hiringSeason: "July - September",
    description: "AI-driven travel technology platform headquartered in Chennai empowering personalized global vacations.",
    featured: false,
  },
  {
    id: "mnc-14",
    name: "Mindtree / LTIMindtree",
    category: "IT Services & Consulting",
    zone: "dlf",
    zoneLabel: "DLF Cybercity (Porur)",
    location: "DLF IT Park, Porur, Chennai",
    packageRange: "₹4.2 LPA - ₹6.8 LPA",
    minCgpa: 6.0,
    roles: ["Software Engineer", "Cloud Associate"],
    skills: ["Java", "C# / .NET", "SQL", "Data Structures"],
    logo: "https://www.ltimindtree.com/favicon.ico",
    website: "https://www.ltimindtree.com/careers",
    hiringSeason: "August - December",
    description: "Global technology consulting and digital solutions firm with engineering hubs in DLF Cybercity.",
    featured: false,
  },
  {
    id: "mnc-15",
    name: "Caterpillar India",
    category: "Product MNC",
    zone: "dlf",
    zoneLabel: "Ascendas & DLF",
    location: "RMZ Millenia Perungudi & DLF Porur, Chennai",
    packageRange: "₹7.5 LPA - ₹12.0 LPA",
    minCgpa: 7.0,
    roles: ["Embedded Software Engineer", "Data & Analytics Trainee"],
    skills: ["C/C++", "Python", "Data Engineering", "Embedded Systems"],
    logo: "https://www.caterpillar.com/favicon.ico",
    website: "https://www.caterpillar.com/en/careers.html",
    hiringSeason: "September - November",
    description: "World's leading manufacturer of heavy equipment operating major R&D software centers in Chennai.",
    featured: false,
  },
  {
    id: "mnc-16",
    name: "Chargebee",
    category: "SaaS Unicorn",
    zone: "siruseri",
    zoneLabel: "Guindy / OMR",
    location: "Guindy, Chennai",
    packageRange: "₹7.0 LPA - ₹14.0 LPA",
    minCgpa: 7.0,
    roles: ["Backend Engineer", "SDET / QA Engineer"],
    skills: ["Java", "Python", "API Design", "PostgreSQL", "AWS"],
    logo: "https://www.chargebee.com/favicon.ico",
    website: "https://www.chargebee.com/careers",
    hiringSeason: "August - November",
    description: "Subscription billing software unicorn founded in Chennai powering global SaaS monetization.",
    featured: false,
  },
];
