// src/utils/pdfGenerator.js
// Generates real educational PDF content on-the-fly using jsPDF.
import { jsPDF } from "jspdf";

/**
 * Generate a real PDF for a lecture note with actual subject content.
 * @param {object} note - note object with title, subject, facultyName, year, pages, description
 * @returns {string} data URL string for the generated PDF
 */
export function generateNotePdf(note) {
  const doc = new jsPDF("p", "mm", "a4");
  const pageW = 210;
  const pageH = 297;
  const margin = 20;
  let y = margin;

  function addPage() {
    doc.addPage();
    y = margin + 5;
  }

  function checkSpace(needed) {
    if (y + needed > pageH - margin - 10) {
      addPage();
    }
  }

  // === Page 1: Cover ===
  // College header bar — Royal Blue
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageW, 6, "F");
  doc.setFillColor(30, 64, 175);
  doc.rect(0, 6, pageW, 2, "F");

  // College name — centered
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(37, 99, 235);
  doc.text("DWARAKA DOSS GOVERDHAN DOSS VAISHNAV COLLEGE", pageW / 2, 25, { align: "center" });

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 140);
  doc.text("Department of Computer Science", pageW / 2, 33, { align: "center" });

  // Decorative line
  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(0.8);
  doc.line(margin, 40, pageW - margin, 40);

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(30, 30, 50);
  const lines = doc.splitTextToSize(note.title, pageW - 2 * margin - 10);
  y = 55;
  doc.text(lines, pageW / 2, y, { align: "center" });

  // Subject & Faculty
  y += 16 + lines.length * 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(80, 80, 120);
  doc.text(`Subject: ${note.subject}`, pageW / 2, y, { align: "center" });
  y += 8;
  doc.text(`Faculty: ${note.facultyName}`, pageW / 2, y, { align: "center" });
  y += 8;
  doc.text(`${note.year === 1 ? "1st" : note.year === 2 ? "2nd" : "3rd"} Year  |  Semester: ${note.semester}  |  Pages: ${note.pages}`, pageW / 2, y, { align: "center" });

  // Bottom bar
  doc.setFillColor(37, 99, 235);
  doc.rect(0, pageH - 14, pageW, 2, "F");
  doc.setFillColor(30, 64, 175);
  doc.rect(0, pageH - 12, pageW, 1, "F");

  // === Content Pages ===
  doc.addPage();
  y = margin + 5;

  const subjectContent = getSubjectContent(note);

  // Page header
  doc.setFillColor(238, 242, 255);
  doc.rect(15, 12, 180, 9, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(37, 99, 235);
  doc.text(`${note.subject} — ${note.title}`, 15, 19);
  doc.text("Page 1", 195, 19, { align: "right" });
  y = 35;
  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(0.3);
  doc.line(15, y, 195, y);
  y += 8;

  // Content
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(40, 40, 60);

  const contentLines = doc.splitTextToSize(subjectContent, 175);
  contentLines.forEach((line) => {
    checkSpace(6);
    doc.text(line, 20, y);
    y += 5.5;
  });

  // Footer on last page
  doc.setFillColor(37, 99, 235);
  doc.rect(0, pageH - 14, pageW, 1, "F");
  doc.setFont("helvetica", "italic");
  doc.setFontSize(7);
  doc.setTextColor(120, 120, 150);
  doc.text("— Generated by DDGDVC Academic Portal —", pageW / 2, pageH - 8, { align: "center" });

  return doc.output("dataurlstring");
}

/**
 * Generate a real PDF for a question paper with actual exam content.
 */
export function generateQuestionPaperPdf(paper) {
  const doc = new jsPDF("p", "mm", "a4");
  const pageW = 210;
  const pageH = 297;
  const margin = 20;
  let y = margin;

  function addPage() {
    doc.addPage();
    y = margin + 5;
  }

  function checkSpace(needed) {
    if (y + needed > pageH - margin - 15) {
      addPage();
    }
  }

  // === Header ===
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageW, 6, "F");
  doc.setFillColor(30, 64, 175);
  doc.rect(0, 6, pageW, 2, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(37, 99, 235);
  doc.text("DWARAKA DOSS GOVERDHAN DOSS VAISHNAV COLLEGE", pageW / 2, 25, { align: "center" });
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 140);
  doc.text("Department of Computer Science", pageW / 2, 33, { align: "center" });

  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(0.8);
  doc.line(margin, 40, pageW - margin, 40);

  // Exam title
  y = 55;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(30, 30, 50);
  doc.text("QUESTION PAPER", pageW / 2, y, { align: "center" });

  y += 14;
  doc.setFontSize(12);
  doc.setTextColor(50, 50, 80);
  const lines = doc.splitTextToSize(paper.title, pageW - 2 * margin - 10);
  doc.text(lines, pageW / 2, y, { align: "center" });

  // Exam info
  y += 14 + lines.length * 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 90);
  doc.text(`Subject: ${paper.subject}`, pageW / 2, y, { align: "center" });
  y += 7;
  doc.text(`Year: ${paper.year}  |  Regulation: ${paper.regulation}  |  Total Pages: ${paper.pages}`, pageW / 2, y, { align: "center" });
  y += 7;
  doc.text(`Faculty: ${paper.facultyName}`, pageW / 2, y, { align: "center" });

  // Instructions
  y += 14;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(37, 99, 235);
  checkSpace(20);
  doc.text("INSTRUCTIONS", margin, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(50, 50, 80);
  const instructions = [
    "1. Answer ALL questions from Part A (10 × 2 = 20 marks)",
    "2. Answer any FIVE questions from Part B (5 × 16 = 80 marks)",
    "3. Draw neat diagrams wherever necessary",
    "4. Use of non-programmable scientific calculator is permitted",
    "5. Duration: 3 Hours  |  Maximum Marks: 100",
  ];
  instructions.forEach((inst) => {
    checkSpace(5);
    doc.text(inst, 20, y);
    y += 5.5;
  });

  // Separator
  y += 6;
  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(0.3);
  checkSpace(5);
  doc.line(margin, y, pageW - margin, y);
  y += 10;

  // === Part A — Questions ===
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(30, 30, 50);
  checkSpace(10);
  doc.text("PART A — Answer ALL Questions (10 × 2 = 20 Marks)", 20, y);
  y += 10;

  const questions = generateExamQuestions(paper.subject);
  questions.slice(0, 10).forEach((q, i) => {
    checkSpace(7);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(50, 50, 80);
    const qText = doc.splitTextToSize(`${i + 1}. ${q}`, 170);
    doc.text(qText, 20, y);
    y += qText.length * 5 + 3;
  });

  // === Part B — Essay Questions ===
  y += 8;
  checkSpace(12);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(30, 30, 50);
  doc.text("PART B — Answer any FIVE Questions (5 × 16 = 80 Marks)", 20, y);
  y += 10;

  questions.slice(10, 18).forEach((q, i) => {
    checkSpace(8);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(50, 50, 80);
    const qText = doc.splitTextToSize(`${i + 1}. ${q}`, 170);
    doc.text(qText, 20, y);
    y += qText.length * 5 + 3;
  });

  // Footer
  doc.setFillColor(37, 99, 235);
  doc.rect(0, pageH - 14, pageW, 2, "F");
  doc.setFillColor(30, 64, 175);
  doc.rect(0, pageH - 12, pageW, 1, "F");
  doc.setFont("helvetica", "italic");
  doc.setFontSize(7);
  doc.setTextColor(100, 100, 140);
  doc.text("— End of Question Paper —", pageW / 2, pageH - 6, { align: "center" });

  return doc.output("dataurlstring");
}

function getSubjectContent(note) {
  const subject = (note.subject || "").toUpperCase().trim();

  // Match known subjects by normalized name
  if (subject.includes("DBMS") || subject.includes("DATABASE")) {
    return `Database Management Systems — ${note.title}
    
Introduction: A Database Management System (DBMS) is software that enables users to define, create, maintain, and control access to databases. It serves as an intermediary between users and the database, ensuring data integrity, security, and efficient retrieval.

Key Concepts:

1. Data Modeling: Entity-Relationship (ER) diagrams represent real-world entities and their relationships. Entities are objects (like Student, Course), attributes describe them (name, ID), and relationships connect them (enrolls_in, teaches).

2. Relational Model: Data is organized into relations (tables) with rows (tuples) and columns (attributes). Each relation has a primary key uniquely identifying each tuple.

3. Normalization: The process of organizing data to reduce redundancy. First Normal Form (1NF) eliminates duplicate columns. Second Normal Form (2NF) removes partial dependencies. Third Normal Form (3NF) removes transitive dependencies. Boyce-Codd Normal Form (BCNF) is a stricter version of 3NF.

4. SQL (Structured Query Language): The standard language for relational database operations. DDL (CREATE, ALTER, DROP) defines structure. DML (SELECT, INSERT, UPDATE, DELETE) manipulates data. DCL (GRANT, REVOKE) controls access.

5. Transaction Management: Transactions are sequences of operations performed as a single logical unit. ACID properties ensure Atomicity, Consistency, Isolation, and Durability. Concurrency control mechanisms like locking and timestamp ordering prevent conflicts.

6. Indexing: Data structures like B+ trees and hash tables speed up data retrieval. Primary indexes are built on the primary key, while secondary indexes can be built on any attribute.

7. Query Processing: The DBMS parses, optimizes, and executes queries. The query optimizer chooses the most efficient execution plan based on cost estimates.`;
  }

  if (subject.includes("OPERATING") || subject.includes("OS")) {
    return `Operating Systems — ${note.title}

Introduction: An Operating System (OS) is system software that manages computer hardware and software resources, providing common services for computer programs. It acts as a mediator between hardware and application software.

Key Concepts:

1. Process Management: A process is a program in execution. The OS manages process creation, scheduling, and termination. Process Control Blocks (PCB) store process information. Context switching allows the CPU to switch between processes efficiently.

2. CPU Scheduling: Algorithms determine which process gets CPU time. First-Come First-Served (FCFS) is simple but can cause convoy effects. Shortest Job First (SJF) minimizes average waiting time. Round Robin (RR) provides fair time-sharing. Priority scheduling ensures important tasks run first.

3. Memory Management: The OS manages physical and virtual memory. Paging divides memory into fixed-size pages, while segmentation divides it into variable-size segments. Virtual memory allows processes to use more memory than physically available through page replacement algorithms like LRU and FIFO.

4. File Systems: The OS provides a hierarchical structure for storing and retrieving data. File allocation methods include contiguous, linked, and indexed allocation. Directory structures range from single-level to tree-structured and acyclic graphs.

5. Deadlocks: A deadlock occurs when processes wait indefinitely for resources held by each other. The four necessary conditions are mutual exclusion, hold-and-wait, no preemption, and circular wait. Prevention, avoidance (Banker's algorithm), and detection-recovery strategies manage deadlocks.

6. I/O Management: The OS manages input/output devices through device drivers. Techniques include programmed I/O, interrupt-driven I/O, and DMA (Direct Memory Access).

7. Disk Scheduling: Algorithms like FCFS, SSTF, SCAN, C-SCAN, LOOK, and C-LOOK optimize disk access times.`;
  }

  if (subject.includes("ASP") || subject.includes(".NET")) {
    return `ASP.NET Development — ${note.title}

Introduction: ASP.NET is a free, cross-platform, open-source framework for building web applications, APIs, and microservices using .NET. It provides a robust, scalable, and secure platform for modern web development.

Key Concepts:

1. ASP.NET Core Architecture: ASP.NET Core follows a modular architecture with middleware pipeline. Each component is a NuGet package, allowing selective inclusion. The Kestrel web server handles HTTP requests, while IIS or Nginx can be used as reverse proxies.

2. MVC Pattern: Model-View-Controller separates application concerns. Models represent data and business logic. Views handle presentation and UI rendering. Controllers process requests, interact with models, and select views. Razor syntax enables server-side HTML generation.

3. Entity Framework Core: An Object-Relational Mapper (ORM) that enables .NET developers to work with databases using .NET objects. It supports Code First approach, Database First, and migrations for schema evolution.

4. Web API Development: RESTful APIs built with ASP.NET Core Web API support JSON/XML serialization, attribute routing, model binding, and validation. Swagger/OpenAPI integration provides interactive documentation.

5. Authentication & Authorization: ASP.NET Core Identity provides user registration, login, and role management. JWT (JSON Web Tokens) enable stateless authentication. OAuth 2.0 and OpenID Connect support external login providers.

6. State Management: Techniques include cookies, sessions, TempData, ViewData, and caching. Distributed caching with Redis improves performance.

7. Deployment & Hosting: ASP.NET Core apps can be deployed to IIS, Azure App Service, Docker containers, Linux servers, or any cloud provider.`;
  }

  if (subject.includes("DMT") || subject.includes("DATA MINING") || subject.includes("DATA WAREHOUS")) {
    return `Data Mining Techniques — ${note.title}

Introduction: Data Mining is the computational process of discovering patterns, correlations, and anomalies in large datasets. It combines methods from statistics, artificial intelligence, machine learning, and database systems.

Key Concepts:

1. Data Preprocessing: Raw data is often incomplete, noisy, and inconsistent. Preprocessing steps include data cleaning (handling missing values, smoothing noisy data), data integration (combining multiple sources), data transformation (normalization, discretization), and data reduction (dimensionality reduction).

2. Association Rule Mining: Discovering interesting relationships between variables in large databases. The Apriori algorithm finds frequent itemsets. Metrics include Support (frequency of itemset), Confidence (conditional probability), and Lift (measure of dependence).

3. Classification: Supervised learning technique that assigns items to predefined categories. Algorithms include Decision Trees (ID3, C4.5, CART), Naive Bayes, K-Nearest Neighbors, Support Vector Machines (SVM), and Neural Networks.

4. Clustering: Unsupervised learning that groups similar items without predefined labels. K-Means partitions data into K clusters. Hierarchical clustering creates dendrograms (agglomerative and divisive). DBSCAN identifies density-based clusters of arbitrary shape.

5. Neural Networks: Computing systems inspired by biological neural networks. Feedforward networks, Convolutional Neural Networks (CNNs) for image processing, Recurrent Neural Networks (RNNs) for sequence data. Backpropagation algorithm trains multi-layer networks.

6. Evaluation: Model evaluation techniques include cross-validation, confusion matrix, precision-recall, ROC curves, and F1-score. Overfitting prevention through regularization and pruning.

7. Applications: Market basket analysis, fraud detection, customer segmentation, recommendation systems, text mining, web mining, and bioinformatics.`;
  }

  // Default content for any other subject
  return `${note.title}

Comprehensive study material covering all key topics, concepts, and practical applications in ${note.subject}.

Introduction: This module provides an in-depth exploration of the core concepts, theoretical foundations, and practical applications in ${note.subject}. Students will gain a thorough understanding of the subject matter through structured content, examples, and case studies.

Key Topics Covered:

1. Fundamentals: Core principles and foundational concepts that form the basis of ${note.subject}. Understanding the history, evolution, and significance of the field.

2. Theoretical Framework: Key theories, models, and frameworks that govern the subject. Mathematical foundations and formal definitions where applicable.

3. Practical Applications: Real-world applications and case studies demonstrating how concepts are applied in industry and research.

4. Algorithms & Methods: Step-by-step examination of algorithms, methodologies, and approaches used in practice.

5. Design & Implementation: Best practices for designing and implementing solutions using the principles of ${note.subject}.

6. Evaluation & Optimization: Techniques for evaluating performance, optimizing solutions, and measuring outcomes.

7. Emerging Trends: Latest developments, research directions, and future trends in ${note.subject}.

This comprehensive coverage ensures students have both theoretical knowledge and practical skills needed to excel in ${note.subject}.`;
}

function generateExamQuestions(subject) {
  const subjUpper = (subject || "").toUpperCase();

  const dbmsQuestions = [
    "Define DBMS and explain its advantages over file-based systems.",
    "Explain the architecture of a DBMS with a neat diagram.",
    "What is an ER diagram? Draw an ER diagram for a university database.",
    "Explain the various types of attributes in ER modeling with examples.",
    "Define the relational model. Explain keys in relational databases.",
    "Write SQL queries to create, insert, update, and delete records in a table.",
    "Explain different types of JOIN operations in SQL with examples.",
    "What is normalization? Explain 1NF, 2NF, and 3NF with examples.",
    "Explain BCNF and how it differs from 3NF.",
    "Describe transaction management and ACID properties in detail.",
    "Explain concurrency control protocols with examples.",
    "What is deadlock? Explain deadlock prevention and detection techniques.",
    "Describe indexing in databases. Compare B+ tree and hash indexing.",
    "Explain query processing and optimization techniques.",
    "Discuss database security mechanisms including authentication and authorization.",
    "Write a detailed note on distributed databases and their advantages.",
    "Explain NoSQL databases and compare them with relational databases.",
    "Describe the role of a Database Administrator (DBA) in an organization.",
  ];

  const osQuestions = [
    "Define Operating System and explain its functions.",
    "Explain the different types of Operating Systems with examples.",
    "Describe the process states and Process Control Block (PCB).",
    "Compare FCFS, SJF, and Round Robin CPU scheduling algorithms.",
    "Explain the concept of deadlock and its necessary conditions.",
    "What is paging? Explain with a neat diagram.",
    "Describe virtual memory and page replacement algorithms.",
    "Explain file allocation methods: contiguous, linked, and indexed.",
    "Describe disk scheduling algorithms: FCFS, SCAN, and C-SCAN.",
    "What is a thread? Differentiate between user-level and kernel-level threads.",
    "Explain the Banker's algorithm for deadlock avoidance.",
    "Describe memory management techniques: Segmentation vs Paging.",
    "Explain I/O management and the role of device drivers.",
    "What is a system call? Explain different types of system calls.",
    "Describe the concept of DMA (Direct Memory Access).",
    "Explain the layered structure of an Operating System.",
    "Compare monolithic kernel vs microkernel architecture.",
    "Describe the Linux file system hierarchy.",
  ];

  const aspNetQuestions = [
    "Define ASP.NET Core and explain its advantages.",
    "Explain the middleware pipeline in ASP.NET Core.",
    "Describe the MVC architecture with a neat diagram.",
    "What is Razor syntax? Explain with examples.",
    "Explain Entity Framework Core and its features.",
    "Describe the Code First approach in Entity Framework.",
    "What are RESTful APIs? Explain with examples.",
    "Explain JWT authentication in ASP.NET Core.",
    "Describe the role of dependency injection in ASP.NET Core.",
    "What is model binding and validation in ASP.NET Core?",
    "Explain state management techniques in ASP.NET.",
    "Describe the deployment options for ASP.NET Core applications.",
    "What are Tag Helpers? Explain with examples.",
    "Explain caching strategies in ASP.NET Core.",
    "Describe SignalR for real-time web functionality.",
    "What is Web API versioning and why is it needed?",
    "Explain OData integration with ASP.NET Core.",
    "Describe microservices architecture with ASP.NET Core.",
  ];

  const dmtQuestions = [
    "Define Data Mining and explain the knowledge discovery process.",
    "Explain data preprocessing techniques in detail.",
    "Describe the Apriori algorithm for association rule mining.",
    "What is classification? Explain Decision Tree algorithm.",
    "Explain K-Means clustering algorithm with an example.",
    "Describe the differences between supervised and unsupervised learning.",
    "What is data normalization? Explain min-max and z-score methods.",
    "Explain the concept of dimensional reduction and PCA.",
    "Describe evaluation metrics for classification models.",
    "What is overfitting? Explain prevention techniques.",
    "Explain neural networks and the backpropagation algorithm.",
    "Describe ensemble methods: Bagging, Boosting, and Random Forest.",
    "What is text mining? Explain its applications.",
    "Describe web mining and its categories.",
    "Explain outlier detection techniques in data mining.",
    "What is time series analysis? Explain its applications.",
    "Describe big data analytics and its challenges.",
    "Explain ethical considerations in data mining.",
  ];

  if (subjUpper.includes("DBMS") || subjUpper.includes("DATABASE")) return dbmsQuestions;
  if (subjUpper.includes("OPERATING") || subjUpper.includes("OS")) return osQuestions;
  if (subjUpper.includes("ASP") || subjUpper.includes(".NET")) return aspNetQuestions;
  if (subjUpper.includes("DMT") || subjUpper.includes("DATA MINING") || subjUpper.includes("DATA WAREHOUS")) return dmtQuestions;

  // Default questions
  return [
    `Define ${subject} and explain its importance in computer science.`,
    "Explain the fundamental concepts with examples.",
    "Describe the architecture and key components.",
    "What are the different types and their applications?",
    "Explain the algorithms used with suitable examples.",
    "Describe the design considerations and trade-offs.",
    "What are the best practices and common pitfalls?",
    "Explain how this concept integrates with other systems.",
    "Describe real-world applications and case studies.",
    "What are the latest developments and future trends?",
    "Compare and contrast different approaches.",
    "Explain performance optimization techniques.",
    "Describe security considerations and best practices.",
    "What testing and validation strategies are used?",
    "Explain deployment and maintenance considerations.",
    "Describe scalability challenges and solutions.",
    "What are the ethical implications and concerns?",
    "Explain how to stay current with evolving technologies.",
  ];
}
