// src/utils/placementMockData.js

export const PLACEMENT_STATS = {
  totalCompanies: 84,
  studentsPlaced: 312,
  highestPackage: 44.5,
  averagePackage: 8.8,
  placementRate: 94.2,
  offersMade: 428,
  yearWise: [
    { year: "2022", placed: 240, highest: 24, avg: 6.2 },
    { year: "2023", placed: 265, highest: 28, avg: 7.1 },
    { year: "2024", placed: 288, highest: 36, avg: 7.9 },
    { year: "2025", placed: 305, highest: 40, avg: 8.4 },
    { year: "2026", placed: 312, highest: 44.5, avg: 8.8 },
  ],
  packageDistribution: [
    { range: "< 5 LPA", count: 45, color: "#94A3B8" },
    { range: "5 - 8 LPA", count: 120, color: "#3B82F6" },
    { range: "8 - 12 LPA", count: 95, color: "#10B981" },
    { range: "12 - 20 LPA", count: 38, color: "#8B5CF6" },
    { range: "20+ LPA", count: 14, color: "#F59E0B" },
  ],
  departmentRates: [
    { dept: "B.Sc CS (Sec A)", rate: 96, placed: 110, total: 115 },
    { dept: "B.Sc CS (Sec B)", rate: 94, placed: 108, total: 115 },
    { dept: "BCA", rate: 92, placed: 65, total: 70 },
    { dept: "M.Sc CS", rate: 97, placed: 29, total: 30 },
  ],
  topRecruiters: [
    { name: "TCS Digital", hires: 42, avgPackage: "7.5 LPA" },
    { name: "Cognizant", hires: 38, avgPackage: "6.8 LPA" },
    { name: "Infosys", hires: 35, avgPackage: "9.5 LPA" },
    { name: "Accenture", hires: 30, avgPackage: "8.5 LPA" },
    { name: "Zoho Corp", hires: 22, avgPackage: "12.0 LPA" },
    { name: "Amazon", hires: 8, avgPackage: "26.0 LPA" },
  ],
};

export const PLACEMENT_NEWS = [
  {
    id: "news-1",
    title: "Google & Microsoft Placement Drives Announced for Batch 2026",
    date: "2026-07-24",
    tag: "Drive Alert",
    summary: "Pre-placement talks scheduled for next week. Eligible candidates must verify their CGPA and submit resumes before Aug 10.",
  },
  {
    id: "news-2",
    title: "Record Package of ₹44.5 LPA Achieved by Department Student!",
    date: "2026-07-20",
    tag: "Achievement",
    summary: "Congratulations to Arjun V (M.Sc CS) for securing a Senior Software Developer offer at Atlassian.",
  },
  {
    id: "news-3",
    title: "Mandatory Aptitude & DSA Boot Camp Starting Next Monday",
    date: "2026-07-15",
    tag: "Training",
    summary: "A 4-week intensive training program covering Quantitative Aptitude, System Design, and Live Coding mock sessions.",
  },
];

export const DETAILED_COMPANY_DRIVES = [
  {
    id: "drive-1",
    companyName: "Google",
    logoUrl: "https://www.google.com/favicon.ico",
    role: "Software Engineer - University Graduate",
    package: 32.0,
    eligibility: "CGPA 8.0+",
    minCgpa: 8.0,
    allowedArrears: 0,
    allowedDepts: ["B.Sc CS", "BCA", "M.Sc CS"],
    skills: ["Data Structures", "Algorithms", "System Design", "C++ / Java / Python"],
    deadline: "2026-08-15",
    driveDate: "2026-08-22",
    location: "Bangalore / Hyderabad / Remote",
    website: "https://careers.google.com",
    status: "Upcoming",
    about: "Google is a global technology leader focused on improving how people connect with information. Our innovations in search, cloud, AI, and consumer hardware drive progress for millions.",
    hiringProcess: ["Online Coding Test (HackerEarth)", "Technical Interview Round 1 (DSA)", "Technical Interview Round 2 (System Design)", "Googliness & Leadership Round"],
    rounds: [
      { name: "Round 1: Online Coding Assessment", duration: "90 Mins", details: "2 LeetCode Medium-Hard DSA problems on Arrays, Trees, Dynamic Programming." },
      { name: "Round 2: Technical Interview I", duration: "45 Mins", details: "Deep dive into Graph algorithms, Complexity optimization, Code quality." },
      { name: "Round 3: Technical Interview II", duration: "45 Mins", details: "Object-oriented design, Data structures tradeoffs, System components." },
      { name: "Round 4: HR & Googliness", duration: "30 Mins", details: "Behavioral questions, Team collaboration, Problem-solving approach." },
    ],
    experience: "The interview panel was very supportive. Focus heavily on code efficiency, boundary test cases, and clear verbal communication of your thought process.",
    tips: [
      "Master Trees, Graphs, and Dynamic Programming.",
      "Practice thinking out loud during mock interviews.",
      "Review time & space complexity analysis thoroughly.",
    ],
    description: "Build scalable software systems, design APIs, and work with cutting-edge AI and cloud technologies serving billions of users worldwide.",
  },
  {
    id: "drive-2",
    companyName: "Microsoft",
    logoUrl: "https://www.microsoft.com/favicon.ico",
    role: "Software Development Engineer (SDE)",
    package: 28.5,
    eligibility: "CGPA 7.5+",
    minCgpa: 7.5,
    allowedArrears: 0,
    allowedDepts: ["B.Sc CS", "BCA", "M.Sc CS"],
    skills: ["C#", "C++", "DSA", "Azure Cloud"],
    deadline: "2026-09-01",
    driveDate: "2026-09-10",
    location: "Hyderabad / Noida",
    website: "https://careers.microsoft.com",
    status: "Upcoming",
    about: "Microsoft enables digital transformation for the era of an intelligent cloud and intelligent edge. Mission: empower every person and organization to achieve more.",
    hiringProcess: ["Codility Assessment", "Technical Interview I", "Technical Interview II", "AA (As Appropriate) Director Round"],
    rounds: [
      { name: "Round 1: Codility Test", duration: "75 Mins", details: "3 problem-solving questions focusing on String manipulation, LinkedLists, and HashMaps." },
      { name: "Round 2: Technical Round 1", duration: "60 Mins", details: "Live coding in C++/C# and CS Fundamentals (OS, Threading, Memory)." },
      { name: "Round 3: Technical Round 2", duration: "60 Mins", details: "System Design for scalable cloud microservices." },
    ],
    experience: "Emphasis is placed on clean, modular code writing and understanding system OS internals.",
    tips: ["Revise Threading, Deadlocks, Virtual Memory, and Tree traversals."],
    description: "Develop enterprise cloud solutions, Windows subsystems, and Azure developer tools.",
  },
  {
    id: "drive-3",
    companyName: "Zoho Corporation",
    logoUrl: "https://www.zoho.com/favicon.ico",
    role: "Member Technical Staff (MTS)",
    package: 12.0,
    eligibility: "CGPA 7.0+",
    minCgpa: 7.0,
    allowedArrears: 1,
    allowedDepts: ["B.Sc CS", "BCA", "M.Sc CS"],
    skills: ["Java", "C", "Data Structures", "Logic & Aptitude"],
    deadline: "2026-07-28",
    driveDate: "2026-08-02",
    location: "Chennai / Tenkasi",
    website: "https://www.zoho.com/careers",
    status: "Ongoing",
    about: "Zoho offers a suite of 55+ cloud applications used by over 100 million users. Known for bootstrapped innovation and product development.",
    hiringProcess: ["Aptitude & C Programming Test", "Basic Programming Round (5 Problems)", "Advanced Programming Round (System Module Design)", "HR & Technical Interview"],
    rounds: [
      { name: "Round 1: Written MCQ Test", duration: "60 Mins", details: "General Aptitude and C Code Output tracing questions." },
      { name: "Round 2: Basic Coding", duration: "120 Mins", details: "Matrix operations, Pattern printing, String parsing without built-in library functions." },
      { name: "Round 3: Advanced System Design", duration: "180 Mins", details: "Design a mini console application like Call Taxi Booking, Railway Reservation, or Banking System." },
    ],
    experience: "Zoho evaluates pure coding logic and hand-rolled data structures. Avoid relying on high-level library shortcuts.",
    tips: ["Practice raw pointer arithmetic, matrix transformations, and OOPs class structure."],
    description: "Develop SaaS products, database engines, and UI frameworks for global software enterprise.",
  },
  {
    id: "drive-4",
    companyName: "TCS Digital",
    logoUrl: "https://www.tcs.com/favicon.ico",
    role: "System Engineer - Digital",
    package: 7.5,
    eligibility: "CGPA 6.0+",
    minCgpa: 6.0,
    allowedArrears: 1,
    allowedDepts: ["B.Sc CS", "BCA", "M.Sc CS"],
    skills: ["Java", "Python", "SQL", "Problem Solving"],
    deadline: "2026-07-30",
    driveDate: "2026-08-05",
    location: "Chennai / Pan India",
    website: "https://www.tcs.com/careers",
    status: "Ongoing",
    about: "Tata Consultancy Services is an IT services, consulting and business solutions organization that has been partnering with many of the world's largest businesses for 50 years.",
    hiringProcess: ["TCS NQT National Test", "Technical Interview", "Managerial & HR Interview"],
    rounds: [
      { name: "Round 1: TCS NQT Cognitive & Tech", duration: "180 Mins", details: "Verbal, Numerical, Reasoning, and Hands-on Coding (2 Questions)." },
      { name: "Round 2: TR & HR Combined", duration: "45 Mins", details: "Questions on Final Year Project, SQL queries, Python/Java fundamentals." },
    ],
    experience: "Be confident about your final year academic project and database normalization concepts.",
    tips: ["Practice TCS NQT past questions and master SQL JOINs."],
    description: "Join high-impact enterprise digital transformation projects across Banking, Healthcare, and Retail.",
  },
  {
    id: "drive-5",
    companyName: "Infosys",
    logoUrl: "https://www.infosys.com/favicon.ico",
    role: "Specialist Programmer (SP)",
    package: 9.5,
    eligibility: "CGPA 6.5+",
    minCgpa: 6.5,
    allowedArrears: 0,
    allowedDepts: ["B.Sc CS", "BCA", "M.Sc CS"],
    skills: ["Python", "JavaScript", "SQL", "Web Dev"],
    deadline: "2026-08-20",
    driveDate: "2026-08-28",
    location: "Chennai / Bangalore",
    website: "https://www.infosys.com",
    status: "Upcoming",
    about: "Infosys is a global leader in next-generation digital services and consulting.",
    hiringProcess: ["HackWithInfy / InfyTQ Test", "Technical Interview", "HR Discussion"],
    rounds: [
      { name: "Round 1: Coding Challenge", duration: "3 Hours", details: "3 Competitive programming problems." },
      { name: "Round 2: Technical Interview", duration: "45 Mins", details: "Project review, Data Structures, Web Technology basics." },
    ],
    experience: "Solid fundamentals in Python and Database management helped score high in the assessment.",
    tips: ["Prepare basic Web concepts (HTML/CSS/JS) along with DBMS."],
    description: "Work on cloud-native applications, API development, and AI-assisted enterprise solutions.",
  },
  {
    id: "drive-6",
    companyName: "Amazon",
    logoUrl: "https://www.amazon.in/favicon.ico",
    role: "SDE-1 (Full Stack)",
    package: 26.0,
    eligibility: "CGPA 7.0+",
    minCgpa: 7.0,
    allowedArrears: 0,
    allowedDepts: ["B.Sc CS", "BCA", "M.Sc CS"],
    skills: ["Java", "AWS", "DSA", "Distributed Systems"],
    deadline: "2026-09-10",
    driveDate: "2026-09-18",
    location: "Chennai / Bangalore",
    website: "https://amazon.jobs",
    status: "Upcoming",
    about: "Amazon strives to be Earth's most customer-centric company, Earth's best employer, and Earth's safest place to work.",
    hiringProcess: ["Online Assessment (OA)", "Technical Interview 1", "Technical Interview 2", "Bar Raiser Interview"],
    rounds: [
      { name: "Round 1: Online Assessment", duration: "120 Mins", details: "2 Coding Questions + Work Style Survey + Amazon Leadership Principles." },
      { name: "Round 2 & 3: Technical Deep Dives", duration: "60 Mins Each", details: "Complex DSA coding on graphs and trees + Low Level Design." },
      { name: "Round 4: Bar Raiser", duration: "60 Mins", details: "Behavioral stories matching Amazon Leadership Principles + LLD." },
    ],
    experience: "Amazon heavily tests Leadership Principles alongside technical proficiency.",
    tips: ["Prepare 2 STAR-method stories for each Leadership Principle."],
    description: "Build robust distributed backend infrastructure for AWS and Amazon Retail.",
  },
  {
    id: "drive-7",
    companyName: "Accenture",
    logoUrl: "https://www.accenture.com/favicon.ico",
    role: "Advanced Application Engineering Associate",
    package: 10.5,
    eligibility: "CGPA 6.5+",
    minCgpa: 6.5,
    allowedArrears: 1,
    allowedDepts: ["B.Sc CS", "BCA", "M.Sc CS"],
    skills: ["Java", "React", "Cloud Basics", "Communication"],
    deadline: "2026-07-20",
    driveDate: "2026-07-25",
    location: "Chennai / Hyderabad",
    website: "https://www.accenture.com/careers",
    status: "Closed",
    about: "Accenture is a leading global professional services company, providing a broad range of services in strategy and consulting, interactive, technology and operations.",
    hiringProcess: ["Cognitive & Technical Assessment", "Coding Assessment", "Communication Assessment", "Interview"],
    rounds: [
      { name: "Round 1: Cognitive & Technical", duration: "90 Mins", details: "MS Office, Networking, Pseudocode, Analytical Ability." },
      { name: "Round 2: Coding", duration: "45 Mins", details: "2 Coding questions." },
    ],
    experience: "Smooth process with emphasis on verbal fluency and logical thinking.",
    tips: ["Brush up on MS Office, basic pseudocode reading, and verbal speed."],
    description: "Develop enterprise cloud solutions and modern web applications.",
  },
];

export const DEMO_STUDENT_PROFILE = {
  name: "Vasanth Kumar",
  rollNo: "23CS104",
  registerNo: "312223104052",
  department: "B.Sc CS",
  section: "A",
  year: "3rd Year",
  graduationYear: 2026,
  cgpa: 8.4,
  activeArrears: 0,
  skills: ["JavaScript", "React", "Python", "SQL", "Data Structures", "Node.js"],
  email: "vasanth.cs23@ddgdvc.edu.in",
  phone: "+91 98765 43210",
  resumeUploaded: true,
  resumeName: "Vasanth_Kumar_Resume_2026.pdf",
};

export const DEMO_STUDENT_APPLICATIONS = [
  {
    id: "app-101",
    companyName: "Zoho Corporation",
    role: "Member Technical Staff (MTS)",
    package: "12.0 LPA",
    appliedDate: "2026-07-10",
    status: "Interview Scheduled",
    stage: 3,
    totalStages: 4,
    nextRound: "Advanced Coding & System Design Round",
    roundDate: "2026-08-02",
    roundTime: "10:00 AM IST",
    venue: "Placement Cell Lab 2 / Online",
  },
  {
    id: "app-102",
    companyName: "TCS Digital",
    role: "System Engineer - Digital",
    package: "7.5 LPA",
    appliedDate: "2026-07-12",
    status: "Shortlisted",
    stage: 2,
    totalStages: 3,
    nextRound: "Technical & HR Interview",
    roundDate: "2026-08-05",
    roundTime: "02:00 PM IST",
    venue: "Main Auditorium",
  },
  {
    id: "app-103",
    companyName: "Google",
    role: "Software Engineer",
    package: "32.0 LPA",
    appliedDate: "2026-07-18",
    status: "Under Review",
    stage: 1,
    totalStages: 4,
    nextRound: "Online Assessment Screening",
    roundDate: "2026-08-22",
    roundTime: "06:00 PM IST",
    venue: "HackerEarth Portal",
  },
  {
    id: "app-104",
    companyName: "Accenture",
    role: "Advanced Application Associate",
    package: "10.5 LPA",
    appliedDate: "2026-07-02",
    status: "Selected",
    stage: 4,
    totalStages: 4,
    nextRound: "Offer Letter Issued",
    roundDate: "2026-07-25",
    roundTime: "Completed",
    venue: "Official Email Notification",
    offerLetterUrl: "#sample-offer-accenture",
  },
];

export const DEMO_OFFER_LETTERS = [
  {
    id: "offer-1",
    companyName: "Accenture India Ltd.",
    role: "Advanced Application Engineering Associate",
    package: "10.5 LPA",
    joiningDate: "2026-09-15",
    location: "Chennai Development Center",
    issueDate: "2026-07-25",
    status: "Accepted",
  },
];

export const APTITUDE_CATEGORIES = [
  {
    id: "quant",
    name: "Quantitative Aptitude",
    icon: "FiTrendingUp",
    topics: ["Number Systems", "Percentages & Averages", "Profit, Loss & Discount", "Time, Speed & Distance", "Permutations & Combinations", "Probability & Statistics"],
    questionCount: 150,
  },
  {
    id: "logical",
    name: "Logical Reasoning",
    icon: "FiCpu",
    topics: ["Blood Relations", "Coding-Decoding", "Syllogisms & Logic", "Seating Arrangement", "Data Sufficiency", "Clocks & Calendars"],
    questionCount: 120,
  },
  {
    id: "verbal",
    name: "Verbal Ability",
    icon: "FiMessageSquare",
    topics: ["Reading Comprehension", "Synonyms & Antonyms", "Sentence Correction", "Para Jumbles", "Idioms & Phrases", "Vocabulary Building"],
    questionCount: 110,
  },
  {
    id: "tech-mcq",
    name: "Technical & CS MCQs",
    icon: "FiTerminal",
    topics: ["Operating Systems", "DBMS & SQL", "Computer Networks", "Data Structures", "Object Oriented Programming (OOPs)", "Web Technologies"],
    questionCount: 200,
  },
];

export const MOCK_QUIZ_QUESTIONS = [
  {
    id: "q1",
    category: "Quantitative Aptitude",
    question: "A train running at a speed of 72 km/hr passes a telegraph pole in 15 seconds. What is the length of the train?",
    options: ["250 meters", "300 meters", "350 meters", "200 meters"],
    correct: 1,
    explanation: "Speed in m/s = 72 * (5/18) = 20 m/s. Distance = Speed * Time = 20 * 15 = 300 meters.",
  },
  {
    id: "q2",
    category: "Logical Reasoning",
    question: "Pointing to a photograph, a man said, 'I have no brother or sister but that man's father is my father's son.' Whose photograph was it?",
    options: ["His own", "His son's", "His father's", "His nephew's"],
    correct: 1,
    explanation: "Since the man has no brother or sister, 'my father's son' is the man himself. So, the man's father is himself, which means it is his son's photograph.",
  },
  {
    id: "q3",
    category: "Technical MCQs",
    question: "Which of the following data structures operates on a Last In, First Out (LIFO) principle?",
    options: ["Queue", "Array", "Stack", "Binary Tree"],
    correct: 2,
    explanation: "Stack uses the LIFO principle where elements added last are removed first.",
  },
  {
    id: "q4",
    category: "Technical MCQs",
    question: "What is the worst-case time complexity of Quick Sort algorithm?",
    options: ["O(n log n)", "O(n)", "O(n^2)", "O(log n)"],
    correct: 2,
    explanation: "In worst-case scenario (e.g. sorted array with poor pivot choice), QuickSort takes O(n^2) time.",
  },
  {
    id: "q5",
    category: "Verbal Ability",
    question: "Select the synonym of the word: IMPEDIMENT",
    options: ["Obstacle", "Assistance", "Clarity", "Speed"],
    correct: 0,
    explanation: "Impediment means a hindrance or obstruction in doing something.",
  },
];

export const CODING_PRACTICE_PROBLEMS = [
  {
    id: "code-1",
    title: "Two Sum",
    difficulty: "Easy",
    language: "Python / C++ / Java / C",
    topic: "Arrays & Hash Map",
    description: "Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`.",
    sampleInput: "nums = [2, 7, 11, 15], target = 9",
    sampleOutput: "[0, 1]",
    constraints: "2 <= nums.length <= 10^4",
    starterCode: {
      python: "def twoSum(nums, target):\n    # Write code here\n    seen = {}\n    for i, num in enumerate(nums):\n        diff = target - num\n        if diff in seen:\n            return [seen[diff], i]\n        seen[num] = i\n    return []",
      cpp: "#include <iostream>\n#include <vector>\n#include <unordered_map>\nusing namespace std;\n\nvector<int> twoSum(vector<int>& nums, int target) {\n    unordered_map<int, int> mp;\n    for(int i=0; i<nums.size(); i++) {\n        int complement = target - nums[i];\n        if(mp.count(complement)) return {mp[complement], i};\n        mp[nums[i]] = i;\n    }\n    return {};\n}",
      java: "import java.util.HashMap;\n\nclass Solution {\n    public int[] twoSum(int[] nums, int target) {\n        HashMap<Integer, Integer> map = new HashMap<>();\n        for (int i = 0; i < nums.length; i++) {\n            int complement = target - nums[i];\n            if (map.containsKey(complement)) {\n                return new int[] { map.get(complement), i };\n            }\n            map.put(nums[i], i);\n        }\n        return new int[]{};\n    }\n}",
    },
  },
  {
    id: "code-2",
    title: "Reverse Linked List",
    difficulty: "Easy",
    language: "Data Structures",
    topic: "Linked List",
    description: "Given the head of a singly linked list, reverse the list and return its head.",
    sampleInput: "head = [1, 2, 3, 4, 5]",
    sampleOutput: "[5, 4, 3, 2, 1]",
    constraints: "Number of nodes is in range [0, 5000]",
    starterCode: {
      python: "# Definition for singly-linked list.\n# class ListNode:\n#     def __init__(self, val=0, next=None):\n#         self.val = val\n#         self.next = next\nclass Solution:\n    def reverseList(self, head):\n        prev = None\n        curr = head\n        while curr:\n            nxt = curr.next\n            curr.next = prev\n            prev = curr\n            curr = nxt\n        return prev",
      cpp: "ListNode* reverseList(ListNode* head) {\n    ListNode* prev = nullptr;\n    ListNode* curr = head;\n    while (curr) {\n        ListNode* nextTemp = curr->next;\n        curr->next = prev;\n        prev = curr;\n        curr = nextTemp;\n    }\n    return prev;\n}",
    },
  },
  {
    id: "code-3",
    title: "SQL Second Highest Salary",
    difficulty: "Medium",
    language: "SQL",
    topic: "Database Queries",
    description: "Write a SQL query to report the second highest salary from the `Employee` table. If there is no second highest salary, return NULL.",
    sampleInput: "Employee table with salaries: [100, 200, 300]",
    sampleOutput: "200",
    constraints: "Standard ANSI SQL",
    starterCode: {
      sql: "SELECT MAX(salary) AS SecondHighestSalary\nFROM Employee\nWHERE salary < (SELECT MAX(salary) FROM Employee);",
    },
  },
];

export const INTERVIEW_PREP_DATA = {
  hrQuestions: [
    {
      q: "Tell me about yourself.",
      guide: "Structure using Past, Present, and Future framework. Keep it under 2 minutes. Highlight your degree in Computer Science, key technical projects, internships, and why you are excited about this role.",
    },
    {
      q: "What are your greatest strengths and weaknesses?",
      guide: "Strengths: Pick analytical thinking, quick learning, or persistence backed by an example. Weaknesses: Choose a real professional area you are working to improve, e.g., speaking in large unfamiliar forums, and show how you are addressing it.",
    },
    {
      q: "Why do you want to join our company?",
      guide: "Research company products, technology stack, company culture, and recent news. Connect their vision with your career aspirations.",
    },
  ],
  techQuestions: [
    {
      topic: "DBMS & SQL",
      q: "Explain ACID properties in DBMS with real-world banking example.",
      a: "Atomicity (All or nothing), Consistency (Database valid state), Isolation (Concurrent transactions don't interfere), Durability (Committed data stays saved even on crash).",
    },
    {
      topic: "Operating Systems",
      q: "What is a Deadlock and what are the 4 necessary conditions for it?",
      a: "Deadlock is a state where processes are blocked waiting for resources held by each other. Conditions: Mutual Exclusion, Hold & Wait, No Preemption, Circular Wait.",
    },
    {
      topic: "Data Structures",
      q: "Difference between BFS and DFS traversal in Graphs.",
      a: "BFS uses Queue (level-by-level, finds shortest path in unweighted graphs). DFS uses Stack/Recursion (explores deep along each branch before backtracking).",
    },
  ],
  gdTopics: [
    {
      title: "Is Artificial Intelligence replacing entry-level software developer jobs?",
      category: "Tech & Economy",
      keyPoints: [
        "AI tools like GitHub Copilot boost developer productivity.",
        "Shift towards higher-level system architecture & problem solving.",
        "Demand for skilled developers who can prompt and verify AI outputs is increasing.",
      ],
    },
    {
      title: "Work From Home vs Work From Office in Tech Companies",
      category: "Workplace",
      keyPoints: [
        "WFH offers flexibility and zero commute time.",
        "WFO fosters team bonding, rapid onboarding, and clear work-life boundaries.",
        "Hybrid model is emerging as the preferred balanced solution.",
      ],
    },
  ],
};

export const TRAINING_MATERIALS = [
  {
    id: "mat-1",
    title: "Complete Quantitative Aptitude Formula Sheet & Shortcuts",
    type: "PDF",
    category: "Aptitude",
    size: "3.4 MB",
    uploadedBy: "Prof. Dr. K. Ramanathan",
    date: "2026-07-15",
    link: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
  },
  {
    id: "mat-2",
    title: "Striver SDE Sheet — Top 180 DSA Interview Questions",
    type: "Coding Sheet",
    category: "DSA & Coding",
    size: "1.2 MB",
    uploadedBy: "Dept Placement Cell",
    date: "2026-07-10",
    link: "https://takeuforward.org/interviews/strivers-sde-sheet-top-coding-interview-problems/",
  },
  {
    id: "mat-3",
    title: "System Design & Object-Oriented Design Lecture Deck",
    type: "PPT",
    category: "System Design",
    size: "14.8 MB",
    uploadedBy: "M P Sudha",
    date: "2026-07-08",
    link: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
  },
  {
    id: "mat-4",
    title: "TCS NQT & Infosys Technical Interview Video Workshop",
    type: "Video",
    category: "Placement Training",
    size: "45 Mins Video",
    uploadedBy: "Placement Cell",
    date: "2026-07-02",
    link: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
];

export const PLACEMENT_CALENDAR_EVENTS = [
  {
    id: "cal-1",
    title: "Zoho Corp - Advanced Coding Round",
    type: "Company Visit",
    date: "2026-08-02",
    time: "10:00 AM - 01:00 PM",
    venue: "Lab 2 & Lab 3",
    badgeColor: "bg-red-500",
  },
  {
    id: "cal-2",
    title: "TCS Digital National Qualifier Test",
    type: "Company Visit",
    date: "2026-08-05",
    time: "09:00 AM - 12:00 PM",
    venue: "Digital Assessment Center",
    badgeColor: "bg-red-500",
  },
  {
    id: "cal-3",
    title: "Google Online Coding Assessment",
    type: "Registration Deadline",
    date: "2026-08-15",
    time: "11:59 PM",
    venue: "Online",
    badgeColor: "bg-amber-500",
  },
  {
    id: "cal-4",
    title: "Mock HR Interview Bootcamp",
    type: "Mock Interview",
    date: "2026-08-10",
    time: "02:00 PM - 05:00 PM",
    venue: "Placement Seminar Hall",
    badgeColor: "bg-emerald-500",
  },
  {
    id: "cal-5",
    title: "Resume Review & LinkedIn Workshop",
    type: "Workshop",
    date: "2026-08-12",
    time: "11:00 AM - 01:00 PM",
    venue: "CS Smart Classroom",
    badgeColor: "bg-purple-500",
  },
];

export const ALUMNI_STORIES = [
  {
    id: "alum-1",
    name: "Sneha Ramachandran",
    batch: "Class of 2024",
    dept: "B.Sc Computer Science",
    company: "Amazon",
    role: "Software Development Engineer (SDE-1)",
    package: "26.0 LPA",
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300",
    story: "I started my preparation in 5th semester by focusing strictly on Data Structures in C++ and participating in LeetCode weekly contests. The placement cell mock interviews helped me build confidence for Amazon's Bar Raiser round.",
    advice: "Don't skip core CS fundamentals like OS and DBMS. Consistency on LeetCode for 6 months makes a huge difference!",
  },
  {
    id: "alum-2",
    name: "Karthik Subramanian",
    batch: "Class of 2025",
    dept: "M.Sc Computer Science",
    company: "Zoho Corporation",
    role: "Member Technical Staff",
    package: "12.0 LPA",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300",
    story: "Zoho focuses on pure logic rather than memorized code templates. Solving pattern printing, custom string parsers, and system design console applications was key during my preparation.",
    advice: "Write clean code without shortcuts. Practice building complete mini applications from scratch in Java or C.",
  },
  {
    id: "alum-3",
    name: "Pooja Venkatesh",
    batch: "Class of 2024",
    dept: "BCA",
    company: "Infosys",
    role: "Specialist Programmer",
    package: "9.5 LPA",
    photo: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=300",
    story: "HackWithInfy was my gateway. The placement cell aptitude bootcamps and coding sheets gave me a structured roadmap to clear all technical rounds.",
    advice: "Form study groups with your classmates to solve aptitude questions and code together daily.",
  },
];

export const PLACEMENT_NOTIFICATIONS = [
  {
    id: "notif-1",
    title: "New Placement Drive: Google SDE 2026",
    category: "New Companies",
    date: "Today at 09:30 AM",
    unread: true,
    urgent: true,
    details: "Google has announced placement drive for 2026 batch. Package: ₹32 LPA. Deadline: Aug 15.",
  },
  {
    id: "notif-2",
    title: "Interview Schedule Released: Zoho MTS Round 3",
    category: "Interview Schedule",
    date: "Yesterday at 04:15 PM",
    unread: true,
    urgent: false,
    details: "Check your student dashboard for individual slot timings on Aug 02.",
  },
  {
    id: "notif-3",
    title: "Accenture Results Declared — 30 Students Placed!",
    category: "Results",
    date: "2026-07-25",
    unread: false,
    urgent: false,
    details: "Congratulations to all selected candidates. Offer letters are available in the dashboard.",
  },
  {
    id: "notif-4",
    title: "Registration Closing Soon: TCS Digital",
    category: "Registration Deadlines",
    date: "2026-07-24",
    unread: false,
    urgent: true,
    details: "Registration closes on July 30th at 11:59 PM. Ensure your CGPA and details are verified.",
  },
];

export const PLACEMENT_FAQS = [
  {
    q: "What is the minimum CGPA required for placement registration?",
    a: "While different companies have different criteria (ranging from 6.0 to 8.0 CGPA), students with a CGPA of 6.0 and above with no active standing arrears are eligible to register for most campus drives.",
  },
  {
    q: "What is the 'One Student, One Offer' policy?",
    a: "Once a student is placed in a non-dream company (package below 10 LPA), they are eligible to apply for 'Dream' companies offering packages above 10 LPA. Once placed in a Dream company, further applications are restricted to allow equal opportunities.",
  },
  {
    q: "How can I update my resume or CGPA in the placement records?",
    a: "Students can update their academic profile and upload updated resumes via the Placement Eligibility & Student Dashboard section. Changes are verified by the Placement Officer.",
  },
  {
    q: "Are attendance requirements mandatory for placement training bootcamps?",
    a: "Yes. Minimum 85% attendance in placement training bootcamps, aptitude sessions, and mock interviews is mandatory to remain eligible for campus placement drives.",
  },
];

export const RESUME_TEMPLATES = [
  { id: "modern", name: "Modern Tech", color: "border-blue-600" },
  { id: "professional", name: "Professional Corporate", color: "border-[#021C4F]" },
  { id: "minimal", name: "Minimalist Clean", color: "border-slate-700" },
];
