// src/utils/placementMockData.js

export const PLACEMENT_STATS = {
  totalCompanies: 28,
  studentsPlaced: 142,
  highestPackage: 16.0,
  averagePackage: 5.8,
  placementRate: 88.75,
  offersMade: 184,
  yearWise: [
    { year: "2022", placed: 118, highest: 10.0, avg: 4.2 },
    { year: "2023", placed: 125, highest: 12.0, avg: 4.8 },
    { year: "2024", placed: 134, highest: 14.0, avg: 5.2 },
    { year: "2025", placed: 138, highest: 15.0, avg: 5.5 },
    { year: "2026", placed: 142, highest: 16.0, avg: 5.8 },
  ],
  packageDistribution: [
    { range: "< 4 LPA", count: 35, color: "#94A3B8" },
    { range: "4 - 6 LPA", count: 68, color: "#3B82F6" },
    { range: "6 - 9 LPA", count: 27, color: "#10B981" },
    { range: "9 - 12 LPA", count: 9, color: "#8B5CF6" },
    { range: "12+ LPA", count: 3, color: "#F59E0B" },
  ],
  departmentRates: [
    { dept: "B.Sc CS (Sec A)", rate: 91, placed: 50, total: 55 },
    { dept: "B.Sc CS (Sec B)", rate: 89, placed: 49, total: 55 },
    { dept: "BCA", rate: 85, placed: 44, total: 52 },
    { dept: "M.Sc CS", rate: 96, placed: 27, total: 28 },
  ],
  topRecruiters: [
    { name: "Zoho Corporation", hires: 18, avgPackage: "8.4 LPA - 12.0 LPA" },
    { name: "TCS (Digital & Ninja)", hires: 34, avgPackage: "3.6 LPA - 7.5 LPA" },
    { name: "Cognizant (GenC)", hires: 28, avgPackage: "4.0 LPA - 6.75 LPA" },
    { name: "Accenture", hires: 22, avgPackage: "4.5 LPA - 6.5 LPA" },
    { name: "Kaar Technologies", hires: 12, avgPackage: "6.5 LPA - 8.0 LPA" },
    { name: "Wipro", hires: 15, avgPackage: "3.5 LPA - 6.5 LPA" },
  ],
};

export const PLACEMENT_NEWS = [
  {
    id: "news-1",
    title: "Zoho Corporation Off-Campus Drive 2026 Announced",
    date: "2026-07-28",
    tag: "Drive Alert",
    summary: "Zoho hiring Member Technical Staff (MTS) for Chennai & Tenkasi campuses. Package: 8.4 LPA - 12.0 LPA. Registration closes Aug 05.",
  },
  {
    id: "news-2",
    title: "TCS NQT 2026 Phase 2 Registration Open for B.Sc CS",
    date: "2026-07-24",
    tag: "TCS Drive",
    summary: "Eligible for Ninja (3.6 LPA) and Digital (7.5 LPA) profiles. Hall tickets will be issued directly by TCS NextStep portal.",
  },
  {
    id: "news-3",
    title: "Kaar Technologies Campus Placement Drive Result Declared",
    date: "2026-07-20",
    tag: "Result Alert",
    summary: "12 Students from DDGDVC B.Sc Computer Science selected as SAP Technical Consultants at 6.5 LPA CTC.",
  },
];

export const DETAILED_COMPANY_DRIVES = [
  {
    id: "drive-1",
    companyName: "Zoho Corporation",
    logoUrl: "https://www.zoho.com/favicon.ico",
    role: "Member Technical Staff (MTS) / Software Engineer",
    package: 8.4,
    eligibility: "CGPA 7.0+",
    minCgpa: 7.0,
    allowedArrears: 1,
    allowedDepts: ["B.Sc CS", "BCA", "M.Sc CS"],
    skills: ["Java", "C", "Data Structures", "Problem Solving", "Object-Oriented Programming"],
    deadline: "2026-08-05",
    driveDate: "2026-08-12",
    location: "Estancia IT Park, Guduvanchery, Chennai / Tenkasi",
    website: "https://www.zoho.com/careers",
    status: "Ongoing",
    about: "Zoho Corporation is an Indian multinational technology company that makes web-based business tools and SaaS applications used by over 100 million users worldwide.",
    hiringProcess: ["Round 1: Aptitude & C Programming MCQs", "Round 2: Basic Programming (5 Problems)", "Round 3: Advanced System Design (Console App)", "Round 4: HR & Technical Discussion"],
    rounds: [
      { name: "Round 1: Written MCQ Test", duration: "60 Mins", details: "General Aptitude and C Code Output tracing questions without compilers." },
      { name: "Round 2: Basic Coding", duration: "120 Mins", details: "Array manipulation, Matrix transformations, and String parsing without built-in library functions." },
      { name: "Round 3: Advanced System Design", duration: "180 Mins", details: "Build a complete mini application like Call Taxi Booking, Railway Reservation, or Banking System in Java/C." },
    ],
    experience: "Zoho evaluates raw programming logic and hand-written data structures. Practice building OOPs applications without using external libraries.",
    tips: [
      "Master raw array/string manipulation in Java or C.",
      "Practice Object-Oriented Design principles (Classes, Encapsulation, Methods).",
      "Avoid using high-level string split or regex shortcuts during coding rounds.",
    ],
    description: "Develop flagship SaaS products, web application engines, and cloud software frameworks for enterprise users globally.",
  },
  {
    id: "drive-2",
    companyName: "TCS Digital & Ninja",
    logoUrl: "https://www.tcs.com/favicon.ico",
    role: "Digital Systems Engineer (7.5 LPA) & Ninja Developer (3.6 LPA)",
    package: 7.5,
    eligibility: "CGPA 6.0+",
    minCgpa: 6.0,
    allowedArrears: 1,
    allowedDepts: ["B.Sc CS", "BCA", "M.Sc CS"],
    skills: ["Python", "Java", "SQL & DBMS", "Aptitude"],
    deadline: "2026-08-10",
    driveDate: "2026-08-18",
    location: "TCS Siruseri / TCS Olympus, Chennai",
    website: "https://www.tcs.com/careers",
    status: "Upcoming",
    about: "Tata Consultancy Services (TCS) is an IT services, consulting, and business solutions organization partnered with the world's largest enterprises.",
    hiringProcess: ["TCS NQT Cognitive & Tech Test", "Technical Interview (TR)", "Managerial & HR Interview (MR/HR)"],
    rounds: [
      { name: "Round 1: TCS NQT Online Test", duration: "165 Mins", details: "Numerical, Verbal, Reasoning Ability + Hands-on Coding (2 Questions)." },
      { name: "Round 2: Technical & HR Interview", duration: "45 Mins", details: "Final Year Academic Project deep-dive, SQL queries, OOPs, and Python/Java basics." },
    ],
    experience: "Strong knowledge of your academic project and SQL JOIN queries will help you clear the TCS Digital interview stream.",
    tips: [
      "Revise DBMS concepts, SQL queries, and normalization.",
      "Practice TCS NQT past national test papers.",
      "Be prepared to explain your final year project architecture clearly.",
    ],
    description: "Implement enterprise digital transformation projects across Banking, Financial Services, Healthcare, and Retail sectors.",
  },
  {
    id: "drive-3",
    companyName: "Cognizant (CTS)",
    logoUrl: "https://www.cognizant.com/favicon.ico",
    role: "GenC Next (6.75 LPA) / GenC Developer (4.0 LPA)",
    package: 6.75,
    eligibility: "CGPA 6.0+",
    minCgpa: 6.0,
    allowedArrears: 0,
    allowedDepts: ["B.Sc CS", "BCA", "M.Sc CS"],
    skills: ["Java", "SQL", "Web Basics", "Problem Solving"],
    deadline: "2026-08-15",
    driveDate: "2026-08-25",
    location: "MEPZ Tambaram / DLF IT Park, Chennai",
    website: "https://www.cognizant.com/careers",
    status: "Upcoming",
    about: "Cognizant is one of the world's leading professional services companies, transforming clients' business, operating, and technology models.",
    hiringProcess: ["GenC Skill Assessment", "Technical Interview", "HR Discussion"],
    rounds: [
      { name: "Round 1: Skill Based Assessment", duration: "120 Mins", details: "Analytical, Debugging, and Coding Assessment." },
      { name: "Round 2: Technical Interview", duration: "30 Mins", details: "Core CS subjects, Data Structures, and basic Web Development Q&A." },
    ],
    experience: "Clean pseudocode explanation and strong verbal communication are highly valued by Cognizant interviewers.",
    tips: ["Practice debugging C/Java pseudocode snippets.", "Review basic HTML, CSS, JavaScript, and SQL SELECT queries."],
    description: "Build cloud applications, API microservices, and enterprise web solutions for Fortune 500 clients.",
  },
  {
    id: "drive-4",
    companyName: "Kaar Technologies",
    logoUrl: "https://www.kaartech.com/favicon.ico",
    role: "SAP Technical Consultant / Associate Software Engineer",
    package: 6.5,
    eligibility: "CGPA 6.5+",
    minCgpa: 6.5,
    allowedArrears: 0,
    allowedDepts: ["B.Sc CS", "BCA", "M.Sc CS"],
    skills: ["C++", "Java", "SQL", "Database Design", "Logic"],
    deadline: "2026-07-15",
    driveDate: "2026-07-22",
    location: "Saligramam / Perungudi, Chennai",
    website: "https://www.kaartech.com",
    status: "Closed",
    about: "Kaar Technologies is a global pure-play SAP consultancy specializing in SAP digital transformation and enterprise software solutions.",
    hiringProcess: ["Aptitude & Programming Test", "Technical Interview 1", "Technical Interview 2", "HR Interview"],
    rounds: [
      { name: "Round 1: Written Test", duration: "90 Mins", details: "Quantitative Aptitude, Logical Reasoning, C/C++ Coding." },
      { name: "Round 2: Technical Interview", duration: "45 Mins", details: "Database Schema design, SQL queries, and Data Structure algorithms." },
    ],
    experience: "12 DDGDVC CS students were selected in the recent drive for SAP ABAP & Cloud Development roles.",
    tips: ["Focus on RDBMS concepts, primary/foreign keys, and relational algebra."],
    description: "Work on global SAP S/4HANA implementations, ABAP programming, and cloud enterprise integration.",
  },
  {
    id: "drive-5",
    companyName: "Accenture India",
    logoUrl: "https://www.accenture.com/favicon.ico",
    role: "Advanced Application Associate (6.5 LPA) / ASE (4.5 LPA)",
    package: 6.5,
    eligibility: "CGPA 6.0+",
    minCgpa: 6.0,
    allowedArrears: 1,
    allowedDepts: ["B.Sc CS", "BCA", "M.Sc CS"],
    skills: ["Python", "Cloud Fundamentals", "Networking", "Problem Solving"],
    deadline: "2026-08-20",
    driveDate: "2026-08-30",
    location: "Sholinganallur / DLF IT Park, Chennai",
    website: "https://www.accenture.com/in-en/careers",
    status: "Upcoming",
    about: "Accenture is a global professional services company with leading capabilities in digital, cloud, and security across 120+ countries.",
    hiringProcess: ["Cognitive & Technical Assessment", "Coding Assessment", "Communication Assessment", "Interview"],
    rounds: [
      { name: "Round 1: Cognitive & Technical", duration: "90 Mins", details: "Pseudocode, MS Office, Networking, Abstract Reasoning." },
      { name: "Round 2: Hands-on Coding", duration: "45 Mins", details: "2 Coding problems testing fundamental algorithms." },
    ],
    experience: "Automated test checks speed and accuracy. Practice pseudocode tracing and verbal clarity.",
    tips: ["Revise MS Office keyboard shortcuts, basic networking (IP/DNS), and pseudocode logic."],
    description: "Design modern cloud applications, enterprise automation tools, and full-stack software solutions.",
  },
  {
    id: "drive-6",
    companyName: "Pickyourtrail",
    logoUrl: "https://pickyourtrail.com/favicon.ico",
    role: "Frontend / Full Stack Software Engineer",
    package: 6.5,
    eligibility: "CGPA 7.0+",
    minCgpa: 7.0,
    allowedArrears: 0,
    allowedDepts: ["B.Sc CS", "BCA", "M.Sc CS"],
    skills: ["React.js", "JavaScript (ES6+)", "HTML5/CSS3", "Node.js"],
    deadline: "2026-08-12",
    driveDate: "2026-08-20",
    location: "Guindy, Chennai",
    website: "https://pickyourtrail.com/careers",
    status: "Upcoming",
    about: "Pickyourtrail is a fast-growing travel-tech platform headquartered in Chennai that uses AI to customize vacation itineraries.",
    hiringProcess: ["Machine Coding Task (React/JS)", "Technical Interview", "Founders Round"],
    rounds: [
      { name: "Round 1: Machine Coding", duration: "150 Mins", details: "Build a responsive web component with API integration in React/JS." },
      { name: "Round 2: Technical Deep Dive", duration: "45 Mins", details: "JavaScript closures, Event loop, Async/Await, and React state management." },
    ],
    experience: "Building real web projects in React gives a huge advantage during Pickyourtrail's practical machine coding round.",
    tips: ["Master JS ES6 features, Promises, Async/Await, and React hooks."],
    description: "Develop customer-facing travel booking engines, dynamic itinerary builders, and mobile-first web applications.",
  },
];

export const DEMO_STUDENT_PROFILE = {
  name: "Vasanth Kumar",
  rollNo: "24E3006",
  registerNo: "312224300601",
  department: "B.Sc CS",
  section: "B",
  year: "3rd Year",
  graduationYear: 2026,
  cgpa: 8.4,
  activeArrears: 0,
  skills: ["JavaScript", "React.js", "Python", "SQL", "Data Structures", "Node.js"],
  email: "vasanth.cs24@ddgdvc.edu.in",
  phone: "+91 98765 43210",
  resumeUploaded: true,
  resumeName: "Vasanth_Kumar_Resume_2026.pdf",
};

export const ALUMNI_STORIES = [
  {
    id: "alum-1",
    name: "Subramanian K",
    batch: "Class of 2025",
    dept: "B.Sc Computer Science (Sec B)",
    company: "Zoho Corporation",
    role: "Member Technical Staff (MTS)",
    package: "12.0 LPA",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300",
    story: "I cleared Zoho's MTS drive by practicing C programming and Java data structures without using built-in library functions. In Round 3, I built a complete Call Taxi Booking System console app within 3 hours. Focus on pure logic!",
    advice: "Do not rely on ready-made library shortcuts. Practice hand-rolled matrix operations, custom string parsing, and clean OOPs design.",
    linkedin: "https://linkedin.com/in/subramanian-zoho",
    companyWebsite: "https://www.zoho.com",
  },
  {
    id: "alum-2",
    name: "Deepika R",
    batch: "Class of 2025",
    dept: "B.Sc Computer Science (Sec A)",
    company: "TCS Digital",
    role: "Systems Engineer - Digital",
    package: "7.5 LPA",
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300",
    story: "I cracked the TCS NQT Digital stream by scoring 100% in the Advanced Coding section. During the technical interview at TCS Siruseri, the panel questioned me thoroughly on my final year database project and SQL JOINs.",
    advice: "Be confident about your final year project. Master SQL normalization and practice past TCS NQT national mock tests.",
    linkedin: "https://linkedin.com/in/deepika-tcs",
    companyWebsite: "https://www.tcs.com",
  },
  {
    id: "alum-3",
    name: "Barath Raj S",
    batch: "Class of 2024",
    dept: "B.Sc Computer Science (Sec B)",
    company: "Kaar Technologies",
    role: "SAP Technical Consultant",
    package: "6.5 LPA",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300",
    story: "Kaar Tech's campus drive at Saligramam evaluated our database schema design and analytical problem solving. My preparation in DBMS and SQL queries helped me land the SAP Consultant role.",
    advice: "Learn relational database design, primary keys, foreign keys, and index tuning. DBMS is tested heavily in enterprise software companies.",
    linkedin: "https://linkedin.com/in/barath-kaartech",
    companyWebsite: "https://www.kaartech.com",
  },
  {
    id: "alum-4",
    name: "Sowmya N",
    batch: "Class of 2024",
    dept: "BCA",
    company: "Accenture India",
    role: "Advanced Application Associate",
    package: "6.5 LPA",
    photo: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=300",
    story: "Accenture's assessment tested speed, pseudocode debugging, and verbal logic. The placement cell aptitude bootcamp prepared me to finish the test with high accuracy.",
    advice: "Work on your verbal fluency and pseudocode reading speed. Daily 30 minutes of aptitude practice goes a long way!",
    linkedin: "https://linkedin.com/in/sowmya-accenture",
    companyWebsite: "https://www.accenture.com",
  },
];

export const APTITUDE_CATEGORIES = [
  {
    id: "quant",
    name: "Quantitative Aptitude",
    topics: ["Number Systems", "Percentages & Averages", "Profit & Loss", "Time & Work", "Speed, Distance & Time", "Probability"],
    questionCount: 150,
  },
  {
    id: "logical",
    name: "Logical Reasoning",
    topics: ["Blood Relations", "Coding-Decoding", "Syllogisms", "Seating Arrangement", "Data Sufficiency", "Clocks & Calendars"],
    questionCount: 120,
  },
  {
    id: "verbal",
    name: "Verbal Ability",
    topics: ["Reading Comprehension", "Synonyms & Antonyms", "Sentence Correction", "Para Jumbles", "Vocabulary"],
    questionCount: 110,
  },
  {
    id: "tech-mcq",
    name: "Technical & CS MCQs",
    topics: ["Operating Systems", "DBMS & SQL", "Computer Networks", "Data Structures", "OOPs in Java/C++"],
    questionCount: 200,
  },
];

export const MOCK_QUIZ_QUESTIONS = [
  {
    id: "q1",
    category: "Quantitative Aptitude",
    question: "A train running at a speed of 72 km/hr passes a telegraph pole in 15 seconds. What is the length of the train?",
    options: ["250 meters", "300 meters", "350 meters", "200 meters"],
    correct: 1,
    explanation: "Speed in m/s = 72 * (5/18) = 20 m/s. Distance = Speed * Time = 20 * 15 = 300 meters.",
  },
  {
    id: "q2",
    category: "Logical Reasoning",
    question: "Pointing to a photograph, a man said, 'I have no brother or sister but that man's father is my father's son.' Whose photograph was it?",
    options: ["His own", "His son's", "His father's", "His nephew's"],
    correct: 1,
    explanation: "Since the man has no brother or sister, 'my father's son' is the man himself. So, the man's father is himself, which means it is his son's photograph.",
  },
  {
    id: "q3",
    category: "Technical MCQs",
    question: "Which of the following data structures operates on a Last In, First Out (LIFO) principle?",
    options: ["Queue", "Array", "Stack", "Binary Tree"],
    correct: 2,
    explanation: "Stack uses the LIFO principle where elements added last are removed first.",
  },
  {
    id: "q4",
    category: "Technical MCQs",
    question: "What is the worst-case time complexity of Quick Sort algorithm?",
    options: ["O(n log n)", "O(n)", "O(n^2)", "O(log n)"],
    correct: 2,
    explanation: "In worst-case scenario (e.g. sorted array with poor pivot choice), QuickSort takes O(n^2) time.",
  },
  {
    id: "q5",
    category: "Verbal Ability",
    question: "Select the synonym of the word: IMPEDIMENT",
    options: ["Obstacle", "Assistance", "Clarity", "Speed"],
    correct: 0,
    explanation: "Impediment means a hindrance or obstruction in doing something.",
  },
];

export const CODING_PRACTICE_PROBLEMS = [
  {
    id: "code-1",
    title: "Two Sum",
    difficulty: "Easy",
    language: "Python / C++ / Java / C",
    topic: "Arrays & Hash Map",
    description: "Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`.",
    sampleInput: "nums = [2, 7, 11, 15], target = 9",
    sampleOutput: "[0, 1]",
    starterCode: {
      python: "def twoSum(nums, target):\n    seen = {}\n    for i, num in enumerate(nums):\n        diff = target - num\n        if diff in seen:\n            return [seen[diff], i]\n        seen[num] = i\n    return []",
      java: "import java.util.HashMap;\n\nclass Solution {\n    public int[] twoSum(int[] nums, int target) {\n        HashMap<Integer, Integer> map = new HashMap<>();\n        for (int i = 0; i < nums.length; i++) {\n            int complement = target - nums[i];\n            if (map.containsKey(complement)) {\n                return new int[] { map.get(complement), i };\n            }\n            map.put(nums[i], i);\n        }\n        return new int[]{};\n    }\n}",
    },
  },
  {
    id: "code-2",
    title: "Reverse Linked List",
    difficulty: "Easy",
    language: "Data Structures",
    topic: "Linked List",
    description: "Given the head of a singly linked list, reverse the list and return its head.",
    sampleInput: "head = [1, 2, 3, 4, 5]",
    sampleOutput: "[5, 4, 3, 2, 1]",
    starterCode: {
      python: "class Solution:\n    def reverseList(self, head):\n        prev = None\n        curr = head\n        while curr:\n            nxt = curr.next\n            curr.next = prev\n            prev = curr\n            curr = nxt\n        return prev",
    },
  },
];

export const INTERVIEW_PREP_DATA = {
  hrQuestions: [
    {
      q: "Tell me about yourself.",
      guide: "Structure using Past, Present, and Future framework. Keep it under 2 minutes. Highlight your degree in Computer Science, key technical projects, internships, and why you are excited about this role.",
    },
    {
      q: "Why do you want to join our company?",
      guide: "Research company products, technology stack, company culture, and recent news. Connect their vision with your career aspirations.",
    },
  ],
  techQuestions: [
    {
      topic: "DBMS & SQL",
      q: "Explain ACID properties in DBMS with real-world banking example.",
      a: "Atomicity (All or nothing), Consistency (Database valid state), Isolation (Concurrent transactions don't interfere), Durability (Committed data stays saved even on crash).",
    },
    {
      topic: "Operating Systems",
      q: "What is a Deadlock and what are the 4 necessary conditions for it?",
      a: "Deadlock is a state where processes are blocked waiting for resources held by each other. Conditions: Mutual Exclusion, Hold & Wait, No Preemption, Circular Wait.",
    },
  ],
  gdTopics: [
    {
      title: "Is Artificial Intelligence replacing entry-level software developer jobs?",
      category: "Tech & Economy",
      keyPoints: [
        "AI tools like GitHub Copilot boost developer productivity.",
        "Shift towards higher-level system architecture & problem solving.",
        "Demand for skilled developers who can prompt and verify AI outputs is increasing.",
      ],
    },
  ],
};

export const RESUME_TEMPLATES = [
  { id: "modern", name: "Modern Tech", color: "border-blue-600" },
  { id: "professional", name: "Professional Corporate", color: "border-[#021C4F]" },
  { id: "minimal", name: "Minimalist Clean", color: "border-slate-700" },
];
